### ISSUE TITLE
UPDATE: Rename "Apps" to "Extensions"

### ISSUE THREAD

**Issue by salmad3** [ignite/apps#115]
### Context:

Following https://github.com/ignite/cli/issues/4235, the "apps" repo requires a refactor to reflect the "extensions" transformation.

### Acceptance Criteria:

- [ ] Update all instances of "Apps" to "Extensions" in app-specific directories @julienrbrt 
- [ ] Update all docs to refer to "Extensions" @julienrbrt @toschdev @salmad3 
- [ ] Update CLI commands and options to use "extensions" @julienrbrt 
- [ ] Establish the new "extensions registry" @julienrbrt @toschdev @salmad3 
- [ ] Rename repo to "extensions" @ilgooz

**Comment by julienrbrt** [comment]
ref: https://github.com/ignite/cli/issues/4235
