### ISSUE TITLE
EPIC: Ignite Network commands documentation - Iteration 2

### ISSUE THREAD

**Issue by lumtis** [ignite/apps#158]
This issue tracks the documentation to the writer for the second iteration of Network commands documentation https://docs.ignite.com/network/introduction

- [ ] Page "launch your testnet on Gitpod" https://github.com/ignite/cli/pull/3377
- [ ] Add a general section (for "chain enthusiast"?) users not interested in being validators but wanting tokens for testnet and participating in coordination for genesis
- [x] Add a doc on how to request accounts with https://github.com/ignite/cli/issues/2945 in general section
- [ ] Add page under coordinator guide for coordinator profile management @fadeev blocked on https://github.com/ignite/apps/issues/161
- [ ] Add page under validator guide for validator profile management @fadeev 
- [ ] Add in publish docs: documentation for initial genesis from config https://github.com/ignite/cli/pull/2950
- [ ] Add more docs on publish option like `--chain-id` https://github.com/ignite/apps/issues/158
- [ ] Document `peer-node` for `join` https://github.com/ignite/cli-plugin-network/pull/11
- [x] Add `remove-account` and `remove-validator` documentation in then general section https://github.com/ignite/cli/issues/2966 https://github.com/ignite/cli/issues/2965
- [ ] Add `change-param` in the general section https://github.com/ignite/cli/issues/2899
- [ ] Add better information on account management @fadeev blocked on https://github.com/ignite/apps/issues/161
- [ ] Add docs for the `AccountBalance` option https://github.com/ignite/apps/issues/158
- [ ] Document Revert Launch https://github.com/ignite/cli-plugin-network/pull/10
