### ISSUE TITLE
EPIC: release advanced Network commands for experimentation

### ISSUE THREAD

**Issue by lumtis** [ignite/apps#159]
Group the list of tasks in order to consider releasing the advanced network commands for experimentation: voucher management and incentivized testnets

- [x] https://github.com/ignite/cli/issues/3117
- [x] https://github.com/ignite/cli/issues/3116
- [x] https://github.com/ignite/cli/issues/1811
- [ ] https://github.com/ignite/apps/issues/153
- [x] https://github.com/ignite/cli/issues/2472
- [x] https://github.com/ignite/cli/issues/2544
- [x] https://github.com/ignite/cli/issues/2947
- [x] https://github.com/ignite/apps/issues/162
- [ ] https://github.com/ignite/cli/issues/3120

**Comment by julienrbrt** [comment]
No need for a tracking issue for this.
