### ISSUE TITLE
UPDATE: Streamline the Structure, Organization, & Processes for Ignite Apps

### ISSUE THREAD

**Issue by michelleellen** [ignite/apps#28]
### Context:

***EDIT: The decision was made to solely maintain core apps developed by the Ignite DevX team, establish an official app registry, and guide community app development externally from this repo.***

Enhance the Ignite Apps repo's structure to clearly showcase the Ignite Marketplace, core Ignite apps, and offer guidelines for community app developers a clear, straightforward initiation path.

### Acceptance Criteria:

- [x] A well-structured README file providing essential information about the app program (https://github.com/ignite/apps/pull/36, https://github.com/ignite/apps/pull/63).
- [ ] Folder structure for apps (https://github.com/ignite/apps/issues/64, https://github.com/ignite/apps/issues/68) ~A folder structure for Official Ignite apps and community built apps that can be used for the Ignite Marketplace UI~
- [ ] Improve docs for on how to use the plugin system.
- [ ] A standardized GitHub template for Ignite apps. This template would serve as a starting point for community members and developers interested in building apps on the Ignite framework. The template could include:

### Expected Outcomes:

- Example usage and integration scenarios to guide developers.
- Contribution guidelines to encourage collaboration within the community.
- An official registry where community members submit app information ~An integration test when community members submit new apps.~
